---
- name: httpd web server
  hosts: all
  tasks:
  - name: Install httpd
    become: true
    ansible.builtin.yum:
      name: httpd
      state: present
  - name: Start service httpd
    become: true
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes