---
- name: Create file on app1
  hosts: stapp01
  tasks:
  - name: Create file
    become: true
    ansible.builtin.file:
      path: /opt/sysops/blog.txt
      state: touch
      owner: root
      group: root
  - name: Set acl
    become: true
    ansible.posix.acl:
      path: /opt/sysops/blog.txt
      entity: tony
      etype: group
      permissions: r
      state: present
- name: Create file on app2
  hosts: stapp02
  tasks:
  - name: Create file
    become: true
    ansible.builtin.file:
      path: /opt/sysops/story.txt
      state: touch
      owner: root
      group: root
  - name: Set acl
    become: true
    ansible.posix.acl:
      path: /opt/sysops/story.txt
      entity: steve
      etype: user
      permissions: rw
      state: present
- name: Create file on app3
  hosts: stapp03
  tasks:
  - name: Create file
    become: true
    ansible.builtin.file:
      path: /opt/sysops/media.txt
      state: touch
      owner: root
      group: root
  - name: Set acl
    become: true
    ansible.posix.acl:
      path: /opt/sysops/media.txt
      entity: banner
      etype: group
      permissions: rw
      state: present
  