---
- name: Create file
  hosts: all
  tasks:
  - name: Create file
    become: true
    ansible.builtin.file:
      path: /opt/nfsdata.txt
      state: touch
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0655