---
- name: httpd web server
  hosts: all
  tasks:
  - name: Create facts.txt
    become: true
    ansible.builtin.blockinfile:
      path: /root/facts.txt
      create: true #creates file if it does not exist
      block: |
        Ansible managed node architecture is {{ ansible_architecture }}
  - name: Install httpd
    become: true
    ansible.builtin.yum:
      name: httpd
      state: present
  - name: Add web content
    become: true
    ansible.builtin.copy:
      remote_src: true
      src: /root/facts.txt
      dest: /var/www/html/index.html
  - name: Start service httpd
    become: true
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
